apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    domain = localhost
    http_port = 3000
    [database]
    type = sqlite3
    path = grafana.db
    [session]
    provider = file
    provider_config = sessions
    cookie_name = grafana_sess
    cookie_secure = false
    session_life_time = 86400
    [analytics]
    check_for_updates = true
    [security]
    admin_user = admin
    admin_password = admin
    [users]
    allow_sign_up = false
    [auth.anonymous]
    enabled = false
    [log]
    mode = console file
    level = info
  provisioning-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
