apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
data:
  config.yaml: |
    model_list:
      - model_name: gpt-3.5-turbo
        litellm_params:
          model: openai/gpt-3.5-turbo
          api_key: sk-your-openai-key
      - model_name: claude-2
        litellm_params:
          model: anthropic/claude-2
          api_key: sk-ant-your-anthropic-key
    general_settings:
      master_key: sk-your-master-key
