apiVersion: v1
kind: Service
metadata:
  name: litellm-proxy-service
  labels:
    app: litellm-proxy
spec:
  selector:
    app: litellm-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
